/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Document;
import org.openapitools.model.DocumentContent;
import java.util.UUID;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-08T17:05:05.140145987+01:00[Europe/Vienna]", comments = "Generator version: 7.10.0")
@Validated
@Tag(name = "documentcontent", description = "the documentcontent API")
public interface DocumentcontentApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /documentcontent : Delete a Model2 object
     *
     * @param id ID of the Model2 object to delete (required)
     * @return Model2 object deleted successfully (status code 204)
     */
    @Operation(
        operationId = "documentcontentDelete",
        summary = "Delete a Model2 object",
        responses = {
            @ApiResponse(responseCode = "204", description = "Model2 object deleted successfully")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/documentcontent"
    )
    
    default ResponseEntity<Void> documentcontentDelete(
        @NotNull @Parameter(name = "id", description = "ID of the Model2 object to delete", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "id", required = true) UUID id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /documentcontent : Get all Model2 objects or search by a query string
     *
     * @param search Search query to filter Model2 objects (optional)
     * @return List of Model2 objects (status code 200)
     */
    @Operation(
        operationId = "documentcontentGet",
        summary = "Get all Model2 objects or search by a query string",
        responses = {
            @ApiResponse(responseCode = "200", description = "List of Model2 objects", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Document.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/documentcontent",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Document>> documentcontentGet(
        @Parameter(name = "search", description = "Search query to filter Model2 objects", in = ParameterIn.QUERY) @Valid @RequestParam(value = "search", required = false) String search
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"file\" : \"\", \"description\" : \"description\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"title\" : \"title\", \"username\" : \"username\" }, { \"file\" : \"\", \"description\" : \"description\", \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"title\" : \"title\", \"username\" : \"username\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /documentcontent/{id} : Get a specific Model2 object by ID
     *
     * @param id ID of the Model2 object to retrieve (required)
     * @return Model2 object retrieved successfully (status code 200)
     *         or Model2 object not found (status code 404)
     */
    @Operation(
        operationId = "documentcontentIdGet",
        summary = "Get a specific Model2 object by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Model2 object retrieved successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentContent.class))
            }),
            @ApiResponse(responseCode = "404", description = "Model2 object not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/documentcontent/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<DocumentContent> documentcontentIdGet(
        @Parameter(name = "id", description = "ID of the Model2 object to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"content\" : \"content\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /documentcontent : Create a new Model2 object
     *
     * @param documentContent  (required)
     * @return Model2 object created successfully (status code 201)
     */
    @Operation(
        operationId = "documentcontentPost",
        summary = "Create a new Model2 object",
        responses = {
            @ApiResponse(responseCode = "201", description = "Model2 object created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentContent.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/documentcontent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DocumentContent> documentcontentPost(
        @Parameter(name = "DocumentContent", description = "", required = true) @Valid @RequestBody DocumentContent documentContent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"content\" : \"content\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /documentcontent : Update an existing Model2 object
     *
     * @param documentContent  (required)
     * @return Model2 object updated successfully (status code 200)
     */
    @Operation(
        operationId = "documentcontentPut",
        summary = "Update an existing Model2 object",
        responses = {
            @ApiResponse(responseCode = "200", description = "Model2 object updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DocumentContent.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/documentcontent",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<DocumentContent> documentcontentPut(
        @Parameter(name = "DocumentContent", description = "", required = true) @Valid @RequestBody DocumentContent documentContent
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"content\" : \"content\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
