version: '1.0'
services:
  paperless_rest_service:
    build: ./rest-service
    container_name: rest_service
    hostname: rest_service
    ports:
      - "8081:8081"
networks:
  swkom3:
    driver: bridge