version: '1.0'
services:
  paperless_rest_service:
    build: ./paperless_rest_service
    container_name: paperless_rest_service
    hostname: paperless_rest_service
    ports:
      - "8081:8081"
networks:
  swkom3:
    driver: bridge