version: '1.0'
services:
  paperless_rest_service:
    build: ./rest-service
    container_name: rest_service
    hostname: rest_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
      - rabbitmq

  paperless_ui_service:
    build: ./ui-service
    container_name: paperless_ui_service
    hostname: paperless_ui_service
    ports:
      - "8080:80"
    depends_on:
      - paperless_rest_service

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres_db
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless123
      POSTGRES_SCHEMA: paperless_schema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management interface port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres_db

volumes:
  postgres_data:
